#对应注册中心的http://${eureka.instance.hostname}:${server.port}/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: third-part-data-project